services:
  mongo:
    image: mongo
    container_name: vitrine-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vitrine-api
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/vitrine
      - JWT_KEY=vitrine_jwt_key
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 3

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: vitrine-web
    depends_on:
      - mongo
      - api
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:4000/api
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongo_data:
